name: Publish package to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: pip
      - name: install build dependencies
        run: python -m pip install build --user
      - name: build package
        run: python -m build --sdist --wheel --outdir dist/
      - name: publish package to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
